version: '3.4'

volumes:
  pgadmin-data:
services:
  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: Microservices/ProductService/Dockerfile
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: Microservices/OrderService/Dockerfile
  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    build:
      context: .
      dockerfile: Microservices/CartService/Dockerfile
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Microservices/UserService/Dockerfile
  webmarketseller:
    image: ${DOCKER_REGISTRY-}webmarketseller
    build:
      context: .
      dockerfile: Applications/WebMarketSeller/Dockerfile
  webmarketdelivery:
    image: ${DOCKER_REGISTRY-}webmarketdelivery
    build:
      context: .
      dockerfile: Applications/WebMarketDelivery/Dockerfile
  webmarketcustomer:
    image: ${DOCKER_REGISTRY-}webmarketcustomer
    build:
      context: .
      dockerfile: Applications/WebMarketCustomer/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15672:15672
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5650:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@webmarket.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin